package view.imageManagers;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import java.awt.Image;
import java.awt.MouseInfo;
import java.awt.Point;
import java.awt.Robot;
import java.awt.Toolkit;
import javax.swing.ImageIcon;
import model.Images;
import view.Dialogs.DialogFileChooser;
import view.PrintComponents;
import view.UI;
import view.UiUtils;

/**
 *
 * @author rafa0
 */
public abstract class ImageManager extends javax.swing.JDialog {

    protected UI parent;
    private int xMousePosition;
    private int yMousePosition;
    private int insertedPhotos = 0;
    public static final int NPHOTOS = 5;
    protected static int selectedPhoto = 1;
    private static String imageDefPath;
    protected static Image myImage;
    private static ImageIcon myIcon;
    protected Images[] suspectImages;

    protected ImageManager(UI parent, boolean modal) {
        super(parent, modal);
        this.parent = parent;
        suspectImages = new Images[NPHOTOS];
        imageDefPath = "view/images/photo-camera (1).png";
        myImage = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource(imageDefPath));
        myIcon = new ImageIcon(myImage);
        initComponents();
        resetImageManager();
        setLocationRelativeTo(null);
        setSize(parent.getWidth(), parent.getHeight());
        hiddeSafePanel();
    }

    /**
     * Se debería usar cada vez que queramos que se vea el form ya que esta
     * pensado para que elimine posibles "residuos" de su anterior visualización
     * como por ejemplo imágenes del anterior sospechoso (si el anterior contaba
     * con más imágenes que el actual)
     */
    public void setImageManager(Images[] img) {
        selectedPhoto = 1;
        insertedPhotos = 0;
        setSuspectImages(img);
        refreshSelectedImage();
        putPhoto();
    }

    protected void setSuspectImages(Images[] images) {
        for (Images image : images) {
            if (image == null) {
                image = new Images(myImage, imageDefPath);
            } else {
                if (image.getImageIcon() != null) {
                    insertedPhotos++;
                }
            }
        }
        suspectImages = images;
    }

    /**
     * Usado al insertar un sospechoso para borrar sus imagenes
     */
    public void resetImageManager() {
        selectedPhoto = 1;
        insertedPhotos = 0;
        for (int i = 0; i < NPHOTOS; i++) {
            suspectImages[i] = new Images(myImage, imageDefPath);
        }
        refreshSelectedImage();
        putPhoto();
        resetLabels();
    }

    public void refreshSelectedImage() {
        jLabel4.setText(selectedPhoto + " / " + NPHOTOS);
    }

    private void putPhoto() {
        if (suspectImages[selectedPhoto - 1] == null) {
            jLabel1.setIcon(myIcon);
            jTextArea1.setText("");
        } else {
            jLabel1.setIcon(suspectImages[selectedPhoto - 1].getImageIcon());
            jTextArea1.setText(suspectImages[selectedPhoto - 1].getDescription());
        }
    }

    public void safeDesc() {
        if (suspectImages != null) {
            if (suspectImages[selectedPhoto - 1] != null) {
                suspectImages[selectedPhoto - 1].setDescription(jTextArea1.getText());
            }
        }
    }

    protected int getInsertedPhotos() {
        return insertedPhotos;
    }

    public Images[] getPhotos() {
        Images[] suspectWellImages = new Images[5];

        for (int i = 0; i < NPHOTOS; i++) {
            if (suspectImages[i] != null) {
                if (suspectImages[i].getImage() == myImage) {
                    suspectWellImages[i] = null;
                } else {
                    suspectWellImages[i] = suspectImages[i];
                }
            } else {
                suspectWellImages[i] = null;
            }

        }

        return suspectWellImages;
    }

    private void hiddeSafePanel() {
        jPanel3.setVisible(false);
        jPanel2.setVisible(true);
        jPanel1.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        btnRemoveImage = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(PrintComponents.getPrimaryColor()
        ));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("¿Desea guardar sus imágenes?");

        jButton4.setBackground(PrintComponents.getPrimaryColor());
        jButton4.setForeground(PrintComponents.getSecundaryColor());
        jButton4.setText("Guardar");
        jButton4.setBorder(javax.swing.BorderFactory.createLineBorder(PrintComponents.getSecundaryColor()));
        jButton4.setFocusable(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setBackground(PrintComponents.getPrimaryColor()   );
        jButton5.setForeground(PrintComponents.getSecundaryColor());
        jButton5.setText("No guardar");
        jButton5.setBorder(javax.swing.BorderFactory.createLineBorder(PrintComponents.getSecundaryColor()));
        jButton5.setFocusable(false);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setBackground(PrintComponents.getPrimaryColor());
        jButton6.setForeground(PrintComponents.getSecundaryColor());
        jButton6.setText("Continuar modificándolas");
        jButton6.setBorder(javax.swing.BorderFactory.createLineBorder(PrintComponents.getSecundaryColor()));
        jButton6.setFocusable(false);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(269, 269, 269)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(142, 142, 142)
                        .addComponent(jLabel5)))
                .addGap(272, 272, 272))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(218, 218, 218)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(220, 220, 220))
        );

        jLabel5.getAccessibleContext().setAccessibleName("");
        jButton4.getAccessibleContext().setAccessibleName("1$0$0");
        jButton5.getAccessibleContext().setAccessibleName("1$0$0");
        jButton6.getAccessibleContext().setAccessibleName("1$0$0");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(PrintComponents.getPrimaryColor()
        ));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/images/icons8-eliminar-20-negro.png"))); // NOI18N
        jButton3.setBorderPainted(false);
        jButton3.setContentAreaFilled(false);
        jButton3.setFocusable(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 27, Short.MAX_VALUE)
        );

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setFocusable(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        jButton2.setFocusable(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        btnRemoveImage.setBackground(PrintComponents.getPrimaryColor()
        );
        btnRemoveImage.setForeground(new java.awt.Color(255, 255, 255));
        btnRemoveImage.setText("Borrar imagen");
        btnRemoveImage.setBorder(javax.swing.BorderFactory.createLineBorder(PrintComponents.getSecundaryColor()
        ));
        btnRemoveImage.setFocusable(false);
        btnRemoveImage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveImageActionPerformed(evt);
            }
        });

        jSeparator1.setForeground(PrintComponents.getPrimaryColor()
        );
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jScrollPane1.setBorder(javax.swing.BorderFactory.createLineBorder(PrintComponents.getPrimaryColor()
        ));

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setBorder(null);
        jScrollPane1.setViewportView(jTextArea1);
        jTextArea1.getAccessibleContext().setAccessibleName("$");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel2.setText("Introduzca si lo desea una descripción de su imagen.");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setForeground(PrintComponents.getPrimaryColor()
        );
        jLabel3.setText("Foto");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setForeground(PrintComponents.getPrimaryColor()
        );
        jLabel4.setText(selectedPhoto+ " / "+ NPHOTOS);

        jSeparator2.setForeground(PrintComponents.getPrimaryColor()
        );
        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(454, 454, 454)
                        .addComponent(btnRemoveImage, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(62, 62, 62)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(495, 495, 495)
                                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(65, 65, 65)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(36, 36, 36)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 425, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(41, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(233, 233, 233)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(208, 208, 208))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(128, 128, 128)
                                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(130, 130, 130)
                                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(26, 26, 26)
                        .addComponent(btnRemoveImage, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE))))
        );

        jButton1.getAccessibleContext().setAccessibleName("$$$");
        jButton1.getAccessibleContext().setAccessibleDescription("icons8-chevron-derecha-en-circulo-40-$"+UiUtils.rgbFormatted(PrintComponents.getPrimaryColor())+"$.png");
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/images/icons8-chevron-derecha-en-circulo-40-$"+UiUtils.rgbFormatted(PrintComponents.getPrimaryColor())+"$.png"))); // NOI18N
        jButton2.getAccessibleContext().setAccessibleName("$$$");
        jButton2.getAccessibleContext().setAccessibleDescription("icons8-chevron-izquierda-en-circulo-40-$"+UiUtils.rgbFormatted(PrintComponents.getPrimaryColor())+"$.png");
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/images/icons8-chevron-izquierda-en-circulo-40-$"+UiUtils.rgbFormatted(PrintComponents.getPrimaryColor())+"$.png"))); // NOI18N
        btnRemoveImage.getAccessibleContext().setAccessibleName("1$0$0");
        btnRemoveImage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                view.EnteredExited.mouseComponentEffect(evt);
            }
        });
        // Code adding the component to the parent container - not shown here
        btnRemoveImage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                view.EnteredExited.mouseComponentEffect(evt);
            }
        });
        jSeparator1.getAccessibleContext().setAccessibleName("$");
        jLabel3.getAccessibleContext().setAccessibleName("-$-$1");
        jLabel4.getAccessibleContext().setAccessibleName("-$-$1");
        jSeparator2.getAccessibleContext().setAccessibleName("$");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.getAccessibleContext().setAccessibleName("0$1$-");
        jPanel1.getAccessibleContext().setAccessibleName("0$1$-");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        if (this instanceof ModifySuspectImageManager) {//Hacer handle abstract
            jPanel3.setVisible(true);
            jPanel2.setVisible(false);
            jPanel1.setVisible(false);
        } else {
            super.dispose();
            setLabels();
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        xMousePosition = evt.getX();
        yMousePosition = evt.getY();
    }//GEN-LAST:event_formMousePressed

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        Point point = MouseInfo.getPointerInfo().getLocation();
        setLocation(point.x - xMousePosition, point.y - yMousePosition);
    }//GEN-LAST:event_formMouseDragged

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        DialogFileChooser y = new DialogFileChooser(this, true);
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        safeDesc();
        if (selectedPhoto == NPHOTOS) {
            selectedPhoto = 1;
        } else {
            selectedPhoto++;
        }
        putPhoto();
        refreshSelectedImage();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnRemoveImageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveImageActionPerformed
        if (insertedPhotos > 0) {
            suspectImages[selectedPhoto - 1] = new Images(myImage, imageDefPath);
            insertedPhotos--;
            putPhoto();
        }
    }//GEN-LAST:event_btnRemoveImageActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        safeDesc();
        if (selectedPhoto == 1) {
            selectedPhoto = NPHOTOS;
        } else {
            selectedPhoto--;
        }
        putPhoto();
        refreshSelectedImage();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        jPanel3.setVisible(false);
        jPanel2.setVisible(true);
        jPanel1.setVisible(true);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        super.dispose();
        hiddeSafePanel();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        safeDesc();
        controller.Controller.getInstance().saveImages(UI.getInstance().getSupectBennModified().getCodeSuspect(), getPhotos());
        setLabels();
        super.dispose();
        hiddeSafePanel();
    }//GEN-LAST:event_jButton4ActionPerformed

    public void addPhoto(Image image, String path) {
        if (suspectImages[selectedPhoto - 1] != null) {
            if (suspectImages[selectedPhoto - 1].getCodeImage() != null) {
                Integer codeImage = suspectImages[selectedPhoto - 1].getCodeImage();
                String description = suspectImages[selectedPhoto - 1].getDescription();
                suspectImages[selectedPhoto - 1] = new Images(image, path);
                suspectImages[selectedPhoto - 1].setCodeImage(codeImage);
                if (description != null) {
                    suspectImages[selectedPhoto - 1].setDescription(description);
                }
            } else {
                suspectImages[selectedPhoto - 1] = new Images(image, path);
                insertedPhotos++;
            }
        } else {
            suspectImages[selectedPhoto - 1] = new Images(image, path);
            insertedPhotos++;
        }
        putPhoto();
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRemoveImage;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    protected javax.swing.JButton jButton3;
    protected javax.swing.JButton jButton4;
    protected javax.swing.JButton jButton5;
    protected javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    protected javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables

    public abstract void setLabels();

    protected abstract void resetLabels();
}
